export default class Translate {
    static translateAuthErrorCodeToUkrainian(errorCode) {
        const errorCodeMap = {
            "auth/admin-restricted-operation": "Операція доступна лише адміністраторам.",
            "auth/argument-error": "Неправильний аргумент.",
            "auth/app-not-authorized": "Додаток не авторизований для використання Firebase Authentication.",
            "auth/app-not-installed": "Додаток не встановлено.",
            "auth/captcha-check-failed": "Перевірка CAPTCHA не вдалася.",
            "auth/code-expired": "Код минув.",
            "auth/cordova-not-ready": "Cordova не готовий.",
            "auth/cors-unsupported": "Цей браузер не підтримує CORS.",
            "auth/credential-already-in-use": "Облікові дані вже використовуються.",
            "auth/custom-token-mismatch": "Невідповідність користувацького токена.",
            "auth/requires-recent-login": "Потрібно нещодавно увійти.",
            "auth/dependent-sdk-initialized-before-auth": "Залежний SDK ініціалізований перед Auth.",
            "auth/dynamic-link-not-activated": "Динамічне посилання не активовано.",
            "auth/email-change-needs-verification": "Зміна email потребує підтвердження.",
            "auth/email-already-in-use": "Email вже використовується.",
            "auth/emulator-config-failed": "Налаштування емулятора не вдалося.",
            "auth/expired-action-code": "Код дії минув.",
            "auth/missing-password": "Введіть будь-ласка пароль",
            "auth/cancelled-popup-request": "Запит на спливаюче вікно скасовано.",
            "auth/internal-error": "Внутрішня помилка.",
            "auth/invalid-api-key": "Недійсний API ключ.",
            "auth/invalid-app-credential": "Недійсні облікові дані додатку.",
            "auth/invalid-app-id": "Недійсний ідентифікатор додатку.",
            "auth/invalid-user-token": "Недійсний токен користувача.",
            "auth/invalid-auth-event": "Недійсна подія авторизації.",
            "auth/invalid-cert-hash": "Недійсний хеш сертифіката.",
            "auth/invalid-verification-code": "Недійсний код перевірки.",
            "auth/invalid-continue-uri": "Недійсна URI продовження.",
            "auth/invalid-cordova-configuration": "Недійсна конфігурація Cordova.",
            "auth/invalid-custom-token": "Недійсний користувацький токен.",
            "auth/invalid-dynamic-link-domain": "Недійсний домен динамічного посилання.",
            "auth/invalid-email": "Недійсний email.",
            "auth/invalid-emulator-scheme": "Недійсна схема емулятора.",
            "auth/invalid-credential": "Недійсні облікові дані.",
            "auth/invalid-message-payload": "Недійсний вміст повідомлення.",
            "auth/invalid-multi-factor-session": "Недійсна сесія багатофакторної аутентифікації.",
            "auth/invalid-oauth-client-id": "Недійсний OAuth Client ID.",
            "auth/invalid-oauth-provider": "Недійсний постачальник OAuth.",
            "auth/invalid-action-code": "Недійсний код дії.",
            "auth/unauthorized-domain": "Неавторизований домен.",
            "auth/wrong-password": "Невірний пароль.",
            "auth/invalid-persistence-type": "Недійсний тип збереження.",
            "auth/invalid-phone-number": "Недійсний номер телефону.",
            "auth/invalid-provider-id": "Недійсний ідентифікатор постачальника.",
            "auth/invalid-recipient-email": "Недійсний email отримувача.",
            "auth/invalid-sender": "Недійсний відправник.",
            "auth/invalid-verification-id": "Недійсний ідентифікатор перевірки.",
            "auth/invalid-tenant-id": "Недійсний ідентифікатор орендаря.",
            "auth/multi-factor-info-not-found": "Інформація про багатофакторну аутентифікацію не знайдена.",
            "auth/multi-factor-auth-required": "Потрібна багатофакторна аутентифікація.",
            "auth/missing-android-pkg-name": "Відсутня назва пакету Android.",
            "auth/missing-app-credential": "Відсутні облікові дані додатку.",
            "auth/auth-domain-config-required": "Потрібна конфігурація домену авторизації.",
            "auth/missing-verification-code": "Відсутній код перевірки.",
            "auth/missing-continue-uri": "Відсутній URI продовження.",
            "auth/missing-iframe-start": "Відсутній старт IFrame.",
            "auth/missing-ios-bundle-id": "Відсутній ідентифікатор пакету iOS.",
            "auth/missing-or-invalid-nonce": "Відсутній або недійсний nonce.",
            "auth/missing-multi-factor-info": "Відсутня інформація про багатофакторну аутентифікацію.",
            "auth/missing-multi-factor-session": "Відсутня сесія багатофакторної аутентифікації.",
            "auth/missing-phone-number": "Відсутній номер телефону.",
            "auth/missing-verification-id": "Відсутній ідентифікатор перевірки.",
            "auth/app-deleted": "Додаток видалено.",
            "auth/account-exists-with-different-credential": "Обліковий запис вже існує з іншими обліковими даними.",
            "auth/network-request-failed": "Мережева помилка.",
            "auth/null-user": "Користувач не знайдений.",
            "auth/no-auth-event": "Подія авторизації не знайдена.",
            "auth/no-such-provider": "Постачальник не знайдений.",
            "auth/operation-not-allowed": "Операція не дозволена.",
            "auth/operation-not-supported-in-this-environment": "Операція не підтримується в цьому середовищі.",
            "auth/popup-blocked": "Спливаюче вікно заблоковано.",
            "auth/popup-closed-by-user": "Спливаюче вікно закрито користувачем.",
            "auth/provider-already-linked": "Постачальник вже прив'язаний.",
            "auth/quota-exceeded": "Перевищено квоту.",
            "auth/redirect-cancelled-by-user": "Перенаправлення скасовано користувачем.",
            "auth/redirect-operation-pending": "Очікується операція перенаправлення.",
            "auth/rejected-credential": "Облікові дані відхилено.",
            "auth/second-factor-already-in-use": "Другий фактор вже використовується.",
            "auth/maximum-second-factor-count-exceeded": "Перевищено максимальну кількість другого фактора.",
            "auth/tenant-id-mismatch": "Невідповідність ідентифікатора орендаря.",
            "auth/timeout": "Час очікування закінчився.",
            "auth/user-token-expired": "Токен користувача минув.",
            "auth/too-many-requests": "Занадто багато запитів. Спробуйте пізніше.",
            "auth/unauthorized-continue-uri": "Неавторизований URI продовження.",
            "auth/unsupported-first-factor": "Перший фактор не підтримується.",
            "auth/unsupported-persistence-type": "Тип збереження не підтримується.",
            "auth/unsupported-tenant-operation": "Операція орендаря не підтримується.",
            "auth/unverified-email": "Email не підтверджено.",
            "auth/user-cancelled": "Користувач скасував.",
            "auth/user-not-found": "Користувач не знайдений.",
            "auth/user-disabled": "Користувача відключено.",
            "auth/user-mismatch": "Невідповідність користувача.",
            "auth/user-signed-out": "Користувач вийшов з системи.",
            "auth/weak-password": "Слабкий пароль.",
            "auth/web-storage-unsupported": "Веб-зберігання не підтримується.",
            "auth/already-initialized": "Вже ініціалізовано.",
            "auth/recaptcha-not-enabled": "reCAPTCHA не увімкнено.",
            "auth/missing-recaptcha-token": "Відсутній токен reCAPTCHA.",
            "auth/invalid-recaptcha-token": "Недійсний токен reCAPTCHA.",
            "auth/invalid-recaptcha-action": "Недійсна дія reCAPTCHA.",
            "auth/missing-client-type": "Відсутній тип клієнта.",
            "auth/missing-recaptcha-version": "Відсутня версія reCAPTCHA.",
            "auth/invalid-recaptcha-version": "Недійсна версія reCAPTCHA.",
            "auth/invalid-req-type": "Недійсний тип запиту."
        };

        return errorCodeMap[errorCode] || `Невідома помилка: ${errorCode}`;
    }
}